// Code generated by scratch. You must modify it.

package complex

import (
	"context"

	"heisenbug/complex/internal/pkg/model"
	desc "heisenbug/complex/pkg/api/complex"
)

// DeleteTemplate stub. Please implement it.
func (i *Implementation) DeleteTemplate(ctx context.Context, TemplateName *desc.DeleteTemplateRequest) (*desc.DeleteTemplateResponse, error) {
	err := i.templateRepo.DeleteTemplate(ctx, &model.Template{Name: TemplateName.GetTemplateName()})
	if err != nil {
		return nil, err
	}
	return &desc.DeleteTemplateResponse{TemplateName: TemplateName.GetTemplateName()}, nil
}
