// Code generated by scratch. You must modify it.

package complex

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	desc "heisenbug/complex/pkg/api/complex"
)

// GetTemplateByName stub. Please implement it.
func (i *Implementation) GetTemplateByName(ctx context.Context, TemplateName *desc.GetTemplateByNameRequest) (*desc.TemplateResponse, error) {
	template, err := i.templateRepo.GetTemplate(ctx, TemplateName.GetTemplateName())
	if err != nil {
		return nil, status.Error(codes.Aborted, err.Error())
	}

	description := ""
	if template.Description != nil {
		description = *template.Description
	}

	return &desc.TemplateResponse{
		Template: &desc.TemplateInfo{
			TemplateName: template.Name,
			Description:  description,
			Status:       template.Status,
		},
	}, nil
}
