// Code generated by scratch. You must modify it.

package complex

import (
	"heisenbug/complex/internal/pkg/repository"
	desc "heisenbug/complex/pkg/api/complex"
)

type Implementation struct {
	desc.UnimplementedComplexServer
	templateRepo repository.Template
}

// NewComplexService return new instance of Implementation.
func NewComplexService(templateRepo repository.Template) *Implementation {
	return &Implementation{
		templateRepo: templateRepo,
	}
}
