// Code generated by scratch. You must modify it.

package public

import (
	"context"
	"fmt"
	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"heisenbug/complex/internal/pkg/model"
	desc "heisenbug/complex/pkg/api/public"
)

// Identification stub. Please implement it.
func (i *Implementation) Identification(ctx context.Context, req *desc.IdentificationRequest) (*desc.IdentificationResponse, error) {
	bind, err := i.templateRepo.GetBindByPhoneNumber(ctx, req.Phone)

	var template *model.Template
	useBind := err == nil

	if useBind {
		template, err = i.templateRepo.GetTemplate(ctx, bind.Name)
		if err != nil {
			return nil, status.Errorf(codes.Internal, "GetTemplateByName error %s", err.Error())
		}
	} else {
		template = &model.Template{
			Status: 0,
		}
	}

	if useBind {
		_ = i.templateRepo.UpdateBindStatusByID(ctx, bind.ID, desc.BindingStatus_COMPLETE)
	}
	fmt.Println("HERE")
	return &desc.IdentificationResponse{
		Id:     uuid.NewString(),
		Status: template.Status,
	}, nil
}
