// Code generated by scratch. You must modify it.

package public

import (
	"heisenbug/complex/internal/pkg/repository"
	desc "heisenbug/complex/pkg/api/public"
)

type Implementation struct {
	desc.UnimplementedPublicServer
	templateRepo repository.Template
}

// NewPublicService return new instance of Implementation.
func NewPublicService(templateRepo repository.Template) *Implementation {
	return &Implementation{
		templateRepo: templateRepo,
	}
}
