// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/external/client.go

// Package external_mock is a generated GoMock package.
package external_mock

import (
	context "context"
	external "heisenbug/identification/internal/pkg/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Identification mocks base method.
func (m *MockClient) Identification(ctx context.Context, phone string) (*external.IdentificationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identification", ctx, phone)
	ret0, _ := ret[0].(*external.IdentificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Identification indicates an expected call of Identification.
func (mr *MockClientMockRecorder) Identification(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identification", reflect.TypeOf((*MockClient)(nil).Identification), ctx, phone)
}
