version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres:15.2
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=complex
    restart: always

volumes:
  postgres: